package burp_magicvars.event;

public enum MagicVarsConfigControllerEvent {
    NEW,
    SAVE,
    DELETE,
    CANCEL,
    TOGGLE_ENABLED,
    MOVE_UP,
    MOVE_DOWN,
    UPDATE_NAME,
    UPDATE_DESCRIPTION,
    UPDATE_INITIAL_VALUE,
    UPDATE_READ_CAPTURE_GROUP,
    UPDATE_WRITE_CAPTURE_GROUP,
    UPDATE_PATH_SCOPE,
    UPDATE_READ_REGEX,
    UPDATE_WRITE_REGEX,
    UPDATE_VARIABLE_TYPE,
    LEFT_VARIABLE_MARKER_CHANGED,
    RIGHT_VARIABLE_MARKER_CHANGED,
    ROW_SELECTION_UPDATE,
    VARIABLES_TABLE_MODEL_CHANGED,
    IMPORT_VARIABLES,
    EXPORT_VARIABLES
}
