package burp_magicvars.event;

public enum MagicVarsConfigModelEvent {
    LAST_VARIABLE_ID_UPDATED,
    CURRENT_VARIABLE_ID_UPDATED,
    CURRENT_VARIABLE_ENABLED_TOGGLE,
    CURRENT_VARIABLE_NAME_UPDATED,
    CURRENT_VARIABLE_TYPE_UPDATED,
    CURRENT_VARIABLE_PATH_SCOPE_UPDATED,
    CURRENT_VARIABLE_READ_REGEX_UPDATED,
    CURRENT_VARIABLE_WRITE_REGEX_UPDATED,
    CURRENT_VARIABLE_READ_CAPTURE_GROUP_UPDATED,
    CURRENT_VARIABLE_WRITE_CAPTURE_GROUP_UPDATED,
    CURRENT_VARIABLE_INITIAL_VALUE_UPDATED,
    CURRENT_VARIABLE_CURRENT_VALUE_UPDATED,
    CURRENT_VARIABLE_CURRENT_VALUE_LAST_UPDATE_UPDATED,
    CURRENT_VARIABLE_DESCRIPTION_UPDATED,
    VARIABLE_LEFT_VARIABLE_MARKER_UPDATED,
    VARIABLE_RIGHT_VARIABLE_MARKER_UPDATED,
    VARIABLE_UPDATED,
    VARIABLE_ADDED,
    VARIABLE_REMOVED,
    VARIABLE_ORDER_UPDATED,
    CURRENT_VARIABLE_SAVE_ERROR,
    EDITOR_STATE_CHANGED
}

